package org.schabi.newpipe.extractor.playlist

import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.ListExtractor.InfoItemsPage
import org.schabi.newpipe.extractor.ListInfo
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.Page
import org.schabi.newpipe.extractor.StreamingService
import org.schabi.newpipe.extractor.exceptions.ExtractionException
import org.schabi.newpipe.extractor.exceptions.ParsingException
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler
import org.schabi.newpipe.extractor.stream.Description
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.utils.ExtractorHelper
import java.io.IOException
import javax.annotation.Nonnull

class PlaylistInfo private constructor(
    serviceId: Int,
    linkHandler: ListLinkHandler,
    name: String
) : ListInfo<StreamInfoItem>(serviceId, linkHandler, name) {

    /**
     * Mixes are handled as particular playlists in NewPipeExtractor. [PlaylistType.NORMAL] is
     * for non-mixes, while other values are for the different types of mixes. The type of a mix
     * depends on how its contents are autogenerated.
     */
    enum class PlaylistType {
        /**
         * A normal playlist (not a mix)
         */
        NORMAL,

        /**
         * A mix made only of streams related to a particular stream, for example YouTube mixes
         */
        MIX_STREAM,

        /**
         * A mix made only of music streams related to a particular stream, for example YouTube
         * music mixes
         */
        MIX_MUSIC,

        /**
         * A mix made only of streams from (or related to) the same channel, for example YouTube
         * channel mixes
         *
         * @deprecated There is currently no service that implements this.
         * YouTube removed all playlists with this type around 2024-06
         */
        @Deprecated("There is currently no service that implements this.")
        MIX_CHANNEL,

        /**
         * A mix made only of streams related to a particular (musical) genre, for example YouTube
         * genre mixes
         */
        MIX_GENRE,
    }

    private var uploaderUrl: String = ""
    private var uploaderName: String = ""
    private var subChannelUrl: String? = null
    private var subChannelName: String? = null
    private var description: Description? = null

    @Nonnull
    private var banners: List<Image> = emptyList()

    @Nonnull
    private var subChannelAvatars: List<Image> = emptyList()

    @Nonnull
    private var thumbnails: List<Image> = emptyList()

    @Nonnull
    private var uploaderAvatars: List<Image> = emptyList()

    private var streamCount: Long = 0
    private var playlistType: PlaylistType? = null

    @Nonnull
    fun getThumbnails(): List<Image> = thumbnails
    fun setThumbnails(thumbnails: List<Image>) {
        this.thumbnails = thumbnails
    }

    @Nonnull
    fun getBanners(): List<Image> = banners
    fun setBanners(banners: List<Image>) {
        this.banners = banners
    }

    fun getUploaderUrl(): String = uploaderUrl
    fun setUploaderUrl(uploaderUrl: String) {
        this.uploaderUrl = uploaderUrl
    }

    fun getUploaderName(): String = uploaderName
    fun setUploaderName(uploaderName: String) {
        this.uploaderName = uploaderName
    }

    @Nonnull
    fun getUploaderAvatars(): List<Image> = uploaderAvatars
    fun setUploaderAvatars(uploaderAvatars: List<Image>) {
        this.uploaderAvatars = uploaderAvatars
    }

    fun getSubChannelUrl(): String? = subChannelUrl
    fun setSubChannelUrl(subChannelUrl: String?) {
        this.subChannelUrl = subChannelUrl
    }

    fun getSubChannelName(): String? = subChannelName
    fun setSubChannelName(subChannelName: String?) {
        this.subChannelName = subChannelName
    }

    @Nonnull
    fun getSubChannelAvatars(): List<Image> = subChannelAvatars
    fun setSubChannelAvatars(subChannelAvatars: List<Image>) {
        this.subChannelAvatars = subChannelAvatars
    }

    fun getStreamCount(): Long = streamCount
    fun setStreamCount(streamCount: Long) {
        this.streamCount = streamCount
    }

    fun getDescription(): Description? = description
    fun setDescription(description: Description?) {
        this.description = description
    }

    fun getPlaylistType(): PlaylistType? = playlistType
    fun setPlaylistType(playlistType: PlaylistType?) {
        this.playlistType = playlistType
    }

    companion object {
        @Throws(IOException::class, ExtractionException::class)
        @JvmStatic
        fun getInfo(url: String): PlaylistInfo {
            return getInfo(NewPipe.getServiceByUrl(url), url)
        }

        @Throws(IOException::class, ExtractionException::class)
        @JvmStatic
        fun getInfo(service: StreamingService, url: String): PlaylistInfo {
            val extractor = service.getPlaylistExtractor(url)
            extractor.fetchPage()
            return getInfo(extractor)
        }

        @Throws(IOException::class, ExtractionException::class)
        @JvmStatic
        fun getMoreItems(
            service: StreamingService,
            url: String,
            page: Page
        ): InfoItemsPage<StreamInfoItem> {
            return service.getPlaylistExtractor(url).getPage(page)
        }

        /**
         * Get PlaylistInfo from PlaylistExtractor
         *
         * @param extractor an extractor where fetchPage() was already called on.
         */
        @Throws(ExtractionException::class)
        @JvmStatic
        fun getInfo(extractor: PlaylistExtractor): PlaylistInfo {
            val info = PlaylistInfo(
                extractor.getServiceId(),
                extractor.getLinkHandler(),
                extractor.getName()
            )
            // collect uploader extraction failures until we are sure this is not
            // just a playlist without an uploader
            val uploaderParsingErrors = mutableListOf<Throwable>()

            try {
                info.setOriginalUrl(extractor.getOriginalUrl())
            } catch (e: Exception) {
                info.addError(e)
            }
            try {
                info.setStreamCount(extractor.getStreamCount())
            } catch (e: Exception) {
                info.addError(e)
            }
            try {
                info.setDescription(extractor.getDescription())
            } catch (e: Exception) {
                info.addError(e)
            }
            try {
                info.setThumbnails(extractor.getThumbnails())
            } catch (e: Exception) {
                info.addError(e)
            }
            try {
                info.setUploaderUrl(extractor.getUploaderUrl())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setUploaderName(extractor.getUploaderName())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setUploaderAvatars(extractor.getUploaderAvatars())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setSubChannelUrl(extractor.getSubChannelUrl())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setSubChannelName(extractor.getSubChannelName())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setSubChannelAvatars(extractor.getSubChannelAvatars())
            } catch (e: Exception) {
                uploaderParsingErrors.add(e)
            }
            try {
                info.setBanners(extractor.getBanners())
            } catch (e: Exception) {
                info.addError(e)
            }
            try {
                info.setPlaylistType(extractor.getPlaylistType())
            } catch (e: Exception) {
                info.addError(e)
            }

            // do not fail if everything but the uploader infos could be collected
            if (uploaderParsingErrors.isNotEmpty()
                && (info.getErrors().isNotEmpty() || uploaderParsingErrors.size < 3)
            ) {
                info.addAllErrors(uploaderParsingErrors)
            }

            val itemsPage = ExtractorHelper.getItemsPageOrLogError(info, extractor)
            info.setRelatedItems(itemsPage.getItems())
            info.setNextPage(itemsPage.getNextPage())

            return info
        }
    }
}
