/// The prim stream must be a balanced bracket sequence — Kotlin turns every
/// ClipPush/GroupPush into a canvas `save()` and every Pop into a `restore()`, so
/// an unbalanced stream either leaks a clip onto the rest of the page or
/// over-restores past the caller's own save. This must hold even when the content
/// stream itself is unbalanced (a `q` with no `Q`, a `W n` never popped).
#[test]
fn prim_stream_brackets_are_balanced_even_for_unbalanced_content() {
    let mut doc = Document::with_version("1.5");
    let ops = vec![
        Operation::new("q", vec![]),
        Operation::new("re", vec![0.into(), 0.into(), 100.into(), 100.into()]),
        Operation::new("W", vec![]),
        Operation::new("n", vec![]),
        Operation::new("q", vec![]),
        Operation::new("re", vec![10.into(), 10.into(), 50.into(), 50.into()]),
        Operation::new("W*", vec![]),
        Operation::new("n", vec![]),
        Operation::new("re", vec![20.into(), 20.into(), 10.into(), 10.into()]),
        Operation::new("f", vec![]),
        // Deliberately no Q at all: the stream ends two levels deep.
    ];
    let page_id = page_from_ops(&mut doc, ops, dictionary! {});

    let page = interpret_page(&doc, page_id).expect("interpret");
    let mut clip = 0i32;
    let mut group = 0i32;
    for p in &page.prims {
        match p {
            Prim::ClipPush { .. } => clip += 1,
            Prim::ClipPop => {
                clip -= 1;
                assert!(clip >= 0, "ClipPop without a matching ClipPush would over-restore");
            }
            Prim::GroupPush { .. } => group += 1,
            Prim::GroupPop => {
                group -= 1;
                assert!(group >= 0, "GroupPop without a matching GroupPush would over-restore");
            }
            _ => {}
        }
    }
    assert_eq!(clip, 0, "{clip} clip level(s) left open at end of stream");
    assert_eq!(group, 0, "{group} group level(s) left open at end of stream");
}

/// §8.4.4: `Q` must pop the clip that the matching `q` scoped, so content after
/// the `Q` is no longer clipped. The pop has to be emitted, or a clip set inside
/// a `q`/`Q` pair silently applies to the whole rest of the page.
#[test]
fn q_pops_a_clip_that_was_committed_inside_its_scope() {
    let mut doc = Document::with_version("1.5");
    let ops = vec![
        Operation::new("q", vec![]),
        Operation::new("re", vec![0.into(), 0.into(), 10.into(), 10.into()]),
        Operation::new("W", vec![]),
        Operation::new("n", vec![]), // committed inside the q
        Operation::new("Q", vec![]),
        Operation::new("rg", vec![0.0.into(), 1.0.into(), 0.0.into()]),
        Operation::new("re", vec![200.into(), 200.into(), 100.into(), 100.into()]),
        Operation::new("f", vec![]),
    ];
    let page_id = page_from_ops(&mut doc, ops, dictionary! {});

    let page = interpret_page(&doc, page_id).expect("interpret");
    let push = page.prims.iter().position(|p| matches!(p, Prim::ClipPush { .. }));
    let pop = page.prims.iter().position(|p| matches!(p, Prim::ClipPop));
    let fill = page
        .prims
        .iter()
        .position(|p| matches!(p, Prim::Fill { .. }))
        .expect("the rect after Q must be filled");
    assert!(push.is_some(), "`W n` inside the q must commit a clip");
    let pop = pop.expect("`Q` must emit the matching ClipPop");
    assert!(
        pop < fill,
        "the clip must be popped BEFORE the later fill, or that fill is clipped to \
         the 10x10 box and disappears"
    );
}

/// §7.4 + §11.6.5.3: a filtered `/SMask` must still produce real alpha. The
/// dangerous failure mode is a filter the underlying library does not implement:
/// if the decode returns an EMPTY buffer instead of an error, every absent sample
/// reads as 0, and because an /SMask sample IS the alpha, the whole base image
/// goes to alpha 0 and the picture vanishes. RunLengthDecode stands in for the
/// commoner DCT case here because it can be generated by hand.
#[test]
fn smask_behind_an_unimplemented_filter_does_not_erase_the_image() {
    let mut doc = Document::with_version("1.5");
    // RunLength: 0x01 => copy the next 2 bytes literally; 0x80 => EOD.
    let smask_id = doc.add_object(Stream::new(
        dictionary! {
            "Type" => "XObject", "Subtype" => "Image",
            "Width" => 2, "Height" => 1,
            "ColorSpace" => "DeviceGray", "BitsPerComponent" => 8,
            "Filter" => "RunLengthDecode",
        },
        vec![0x01, 0x00, 0xFF, 0x80],
    ));
    let stream = Stream::new(
        dictionary! {
            "Type" => "XObject", "Subtype" => "Image",
            "Width" => 2, "Height" => 1,
            "ColorSpace" => "DeviceGray", "BitsPerComponent" => 8,
            "SMask" => smask_id,
        },
        vec![0xFF, 0xFF],
    );
    let img = extract_image(&doc, &stream, 0xFF00_0000, &no_cs()).expect("image must decode");
    let a = alphas(&img);
    assert!(
        a.iter().any(|&v| v > 0),
        "a filtered /SMask that fails to decode must not zero the alpha of the whole \
         image — that renders the picture completely invisible; got {a:?}"
    );
    assert_eq!(
        a, vec![0, 255],
        "the RunLength-encoded /SMask must decode to the same alphas as an \
         unfiltered one"
    );
}

// ===========================================================================
// Primitive and operator caps
//
// Three caps sit in series on the path from content stream to canvas:
// MAX_CONTENT_OPS (Rust, operators read), MAX_PRIMITIVES (Rust, prims emitted),
// and SafePdfParser.MAX_PRIMITIVES (Kotlin, prims decoded). The *smallest* one
// binds, so raising only the last cannot change what a dense page renders.

/// A page with far more content than the caps allow must render a truncated but
/// structurally valid page — never zero prims, never an unbalanced bracket
/// stream, never a panic.
///
/// The amount of content is DERIVED from the caps rather than hardcoded, so this
/// keeps testing the right thing when a cap moves and does not false-fail on a
/// legitimate change. What it does pin is the cap *relationship*, which is where
/// the real bug lives: three caps sit in series on the path from content stream to
/// canvas — `MAX_CONTENT_OPS` (operators read), `MAX_PRIMITIVES` (prims emitted),
/// and the consumer's own bound — and the smallest binds. When `MAX_CONTENT_OPS`
/// was 200_000 the operator cap bound first at ~100k prims, which made
/// `MAX_PRIMITIVES` dead and made raising the consumer-side bound a no-op.
#[test]
fn content_beyond_the_caps_truncates_to_a_valid_page() {
    // For the simplest content, one `re f` pair is 2 operators and 1 prim, so the
    // operator cap must leave room for MAX_PRIMITIVES prims or it binds first and
    // MAX_PRIMITIVES becomes unreachable.
    assert!(
        MAX_CONTENT_OPS >= 2 * MAX_PRIMITIVES,
        "cap ordering is inverted: MAX_CONTENT_OPS ({MAX_CONTENT_OPS}) must leave \
         room for MAX_PRIMITIVES ({MAX_PRIMITIVES}) prims at 2 operators each, or \
         the operator cap binds first and MAX_PRIMITIVES is dead code — which also \
         makes any larger consumer-side bound unreachable"
    );

    let mut doc = Document::with_version("1.5");
    let ceiling = (MAX_CONTENT_OPS / 2).min(MAX_PRIMITIVES);
    let pairs = ceiling + 500;
    let mut raw = String::with_capacity(pairs * 18);
    raw.push_str("1 0 0 rg\n");
    for i in 0..pairs {
        let y = (i % 700) as i32;
        raw.push_str(&format!("10 {y} 2 2 re f\n"));
    }
    let page_id = assemble(
        &mut doc,
        raw.into_bytes(),
        dictionary! {},
        dictionary! {},
        dictionary! {},
    );

    let page = interpret_page(&doc, page_id).expect("an over-long content stream must not lose the page");
    let fills = count(&page.prims, |p| matches!(p, Prim::Fill { .. }));
    println!(
        "caps: requested {pairs} fills, emitted {fills} (ceiling {ceiling}); \
         MAX_CONTENT_OPS={MAX_CONTENT_OPS} MAX_PRIMITIVES={MAX_PRIMITIVES}"
    );
    assert!(fills > 0, "a truncated page must still render its leading content");
    assert!(
        fills < pairs,
        "the caps must actually bind or this test proves nothing (emitted all {fills})"
    );
    assert!(
        fills <= ceiling + 1,
        "emitted {fills} fills, past the {ceiling} the caps allow"
    );
    // Balanced, so a consumer's save/restore stack cannot be corrupted by truncation.
    let mut depth = 0i32;
    for p in &page.prims {
        match p {
            Prim::ClipPush { .. } => depth += 1,
            Prim::ClipPop => depth -= 1,
            _ => {}
        }
        assert!(depth >= 0, "truncation must not emit an unmatched ClipPop");
    }
    assert_eq!(depth, 0, "truncation must leave the clip stack balanced");
}

/// Reaching `MAX_PRIMITIVES` must not corrupt the bracket structure. This is the
/// one case where the cap value genuinely matters: bracket-closing prims are
/// pushed UNGUARDED (the `while clip_depth > 0` / `while group_depth > 0` drains),
/// while content emission stops at the cap. If a truncation ever landed between a
/// ClipPush and its ClipPop the clip would never be restored and everything after
/// it on the page would be clipped away — or, on the consumer side, the canvas
/// save/restore stack would desynchronise.
///
/// Clips are opened and left open across the point where the cap is hit, because a
/// cap reached with NO brackets open proves nothing about bracket integrity.
/// Deliberately built from plain path operators rather than a tiling pattern: how
/// many prims a pattern yields is an implementation choice (a periodic pattern may
/// collapse to a single `ImageTiled`), and this test must not depend on it.
#[test]
fn exceeding_the_primitive_cap_keeps_the_bracket_structure_intact() {
    let mut doc = Document::with_version("1.5");
    let mut raw = String::with_capacity(MAX_PRIMITIVES * 18);
    // Open several nested clips and never close them, so the cap is reached while
    // brackets are outstanding and the unguarded drains have real work to do.
    const NESTING: usize = 6;
    for k in 0..NESTING {
        let s = 10 * k;
        raw.push_str(&format!("q\n{s} {s} 380 380 re W n\n"));
    }
    raw.push_str("1 0 0 rg\n");
    // Comfortably past MAX_PRIMITIVES; emission stops at the cap so the surplus is
    // cheap, and each `re f` pair stays well inside MAX_CONTENT_OPS.
    let pairs = MAX_PRIMITIVES + 2_000;
    for i in 0..pairs {
        let y = (i % 380) as i32;
        raw.push_str(&format!("10 {y} 2 2 re f\n"));
    }
    let page_id = assemble(
        &mut doc,
        raw.into_bytes(),
        dictionary! {},
        dictionary! { "MediaBox" => vec![0.into(), 0.into(), 400.into(), 400.into()] },
        dictionary! {},
    );

    let page = interpret_page(&doc, page_id).expect("interpret");
    println!(
        "primitive cap: emitted {} prims (MAX_PRIMITIVES={MAX_PRIMITIVES}), \
         {NESTING} clips left open by the content",
        page.prims.len()
    );
    assert!(
        page.prims.len() >= MAX_PRIMITIVES,
        "this test only means something if it actually reaches the cap; got {} of \
         {MAX_PRIMITIVES}. Raise `pairs` — do NOT lower this assertion, or the \
         checks below stop covering the truncation path.",
        page.prims.len()
    );
    assert!(
        count(&page.prims, |p| matches!(p, Prim::ClipPush { .. })) >= NESTING,
        "the nested clips must actually be committed, or nothing is at risk"
    );
    // The overshoot bound is not a tidy formula, so assert the property that
    // actually makes truncation safe: NO VISIBLE INK may appear past the cap.
    // Content emission is gated per-push, so drawing stops exactly at the cap; what
    // spills over is bracket bookkeeping. Note it is NOT only closers — a form's
    // mandatory /BBox ClipPush can also land past the cap, immediately followed by
    // its pop. That is why a consumer clamp must sit above the WHOLE overshoot, not
    // merely above the cap: cutting anywhere inside it unbalances the brackets even
    // though no drawing is lost.
    let overshoot: Vec<&Prim> = page.prims.iter().skip(MAX_PRIMITIVES).collect();
    println!("  overshoot: {} prim(s) past the cap", overshoot.len());
    for (i, p) in overshoot.iter().enumerate() {
        assert!(
            !is_ink(p),
            "prim {} past the cap puts ink on the page — a guard is gating \
             per-operator instead of per-emit, so a consumer truncating the tail \
             would silently drop visible drawing",
            MAX_PRIMITIVES + i
        );
    }
    let mut clip = 0i32;
    let mut group = 0i32;
    for (i, p) in page.prims.iter().enumerate() {
        match p {
            Prim::ClipPush { .. } => clip += 1,
            Prim::ClipPop => {
                clip -= 1;
                assert!(clip >= 0, "unmatched ClipPop at prim {i} would over-restore the canvas");
            }
            Prim::GroupPush { .. } => group += 1,
            Prim::GroupPop => {
                group -= 1;
                assert!(group >= 0, "unmatched GroupPop at prim {i} would over-restore the canvas");
            }
            _ => {}
        }
    }
    assert_eq!(clip, 0, "{clip} clip level(s) left open when the primitive cap was hit — a truncation landed between a ClipPush and its ClipPop, so the rest of the page is clipped away");
    assert_eq!(group, 0, "{group} group level(s) left open at the primitive cap");
}

/// The same invariant, but with the cap crossed PART-WAY THROUGH a single
/// operator. A `Do` is one operator that can emit unboundedly many prims, so this
/// is where the count would run past the cap if the guards were per-operator
/// rather than per-emit. It also crosses while the form's own mandatory `/BBox`
/// clip (§8.10.2) is open, on top of the page's clips, so the bracket at risk is
/// one the content stream never explicitly closes.
///
/// Kept separate from the plain-operator case above, and deliberately using a form
/// XObject rather than a tiling pattern: how many prims a pattern yields is an
/// implementation choice, and coupling this to it once blocked a legitimate tiling
/// coverage fix.
#[test]
fn crossing_the_primitive_cap_mid_operator_keeps_the_bracket_structure_intact() {
    let mut doc = Document::with_version("1.5");
    let per_form = MAX_PRIMITIVES / 2 + 1_000;
    let mut form = String::with_capacity(per_form * 18);
    form.push_str("q\n5 5 380 380 re W n\n1 0 0 rg\n");
    for i in 0..per_form {
        let y = (i % 370) as i32;
        form.push_str(&format!("10 {y} 2 2 re f\n"));
    }
    // No closing Q: the form's clip is drained by the interpreter, not the content.
    let form_id = doc.add_object(Stream::new(
        dictionary! {
            "Type" => "XObject", "Subtype" => "Form",
            "BBox" => vec![0.into(), 0.into(), 400.into(), 400.into()],
        },
        form.into_bytes(),
    ));
    // Two page-level clips, then three `Do`s. The cap lands inside the second or
    // third one, i.e. inside a single operator.
    let mut ops = Vec::new();
    for k in 0..2 {
        let s = 10 * k;
        ops.push(Operation::new("q", vec![]));
        ops.push(Operation::new("re", vec![s.into(), s.into(), 380.into(), 380.into()]));
        ops.push(Operation::new("W", vec![]));
        ops.push(Operation::new("n", vec![]));
    }
    for _ in 0..3 {
        ops.push(Operation::new("Do", vec![Object::Name(b"Fm0".to_vec())]));
    }
    let bytes = Content { operations: ops }.encode().unwrap();
    let page_id = assemble(
        &mut doc,
        bytes,
        dictionary! { "XObject" => dictionary! { "Fm0" => form_id } },
        dictionary! { "MediaBox" => vec![0.into(), 0.into(), 400.into(), 400.into()] },
        dictionary! {},
    );

    let page = interpret_page(&doc, page_id).expect("interpret");
    println!(
        "mid-operator cap: emitted {} prims (MAX_PRIMITIVES={MAX_PRIMITIVES})",
        page.prims.len()
    );
    assert!(
        page.prims.len() >= MAX_PRIMITIVES,
        "this test only means something if it actually reaches the cap; got {} of \
         {MAX_PRIMITIVES}. Raise `per_form` or the `Do` count — do NOT lower this \
         assertion.",
        page.prims.len()
    );
    // The point of this variant: an operator that WANTS to emit ~150k more prims
    // must still not put any ink past the cap, because content emission is gated
    // per-push and stops mid-operator. Bracket bookkeeping may spill over — here the
    // third `Do`'s mandatory /BBox ClipPush lands past the cap and is popped
    // immediately — but no drawing may.
    let overshoot: Vec<&Prim> = page.prims.iter().skip(MAX_PRIMITIVES).collect();
    let kind = |p: &Prim| match p {
        Prim::Fill { .. } => "Fill",
        Prim::Stroke { .. } => "Stroke",
        Prim::Text { .. } => "Text",
        Prim::Image { .. } => "Image",
        Prim::ImageTiled { .. } => "ImageTiled",
        Prim::ClipPush { .. } => "ClipPush",
        Prim::ClipPop => "ClipPop",
        Prim::GroupPush { .. } => "GroupPush",
        Prim::GroupPop => "GroupPop",
        Prim::SoftMaskPush { .. } => "SoftMaskPush",
        Prim::SoftMaskContent => "SoftMaskContent",
        Prim::SoftMaskPop => "SoftMaskPop",
        _ => "other",
    };
    println!(
        "  overshoot: {} prim(s) past the cap: {:?}",
        overshoot.len(),
        overshoot.iter().map(|p| kind(p)).collect::<Vec<_>>()
    );
    for (i, p) in overshoot.iter().enumerate() {
        assert!(
            !is_ink(p),
            "prim {} past the cap is {} and puts ink on the page — a guard is gating \
             per-operator instead of per-emit, so a consumer truncating the tail \
             would silently drop visible drawing",
            MAX_PRIMITIVES + i,
            kind(p)
        );
    }
    let mut clip = 0i32;
    let mut group = 0i32;
    for (i, p) in page.prims.iter().enumerate() {
        match p {
            Prim::ClipPush { .. } => clip += 1,
            Prim::ClipPop => {
                clip -= 1;
                assert!(clip >= 0, "unmatched ClipPop at prim {i} would over-restore the canvas");
            }
            Prim::GroupPush { .. } => group += 1,
            Prim::GroupPop => {
                group -= 1;
                assert!(group >= 0, "unmatched GroupPop at prim {i} would over-restore the canvas");
            }
            _ => {}
        }
    }
    assert_eq!(
        clip, 0,
        "{clip} clip level(s) left open — the form's mandatory /BBox clip was not \
         drained when the cap was hit mid-operator, so the rest of the page is \
         clipped away"
    );
    assert_eq!(group, 0, "{group} group level(s) left open at the primitive cap");
}

// ===========================================================================
// 11. Inline images — §8.9.7
// These are the acceptance criteria for the lenient content-stream tokenizer.
// lopdf's `Content::decode` is all-or-nothing, so a single inline image it
// cannot handle drops the ENTIRE operator list and the page degrades to
// annotations only. Each test therefore also asserts that the operators AFTER
// the inline image still ran — that is the part that actually loses pages.

/// Wrap raw inline-image bytes in a content stream with a marker fill after it,
/// so a test can tell "the image was skipped" from "the whole stream was lost".
fn inline_image_page(doc: &mut Document, bi: &[u8]) -> ObjectId {
    let mut c: Vec<u8> = Vec::new();
    c.extend_from_slice(b"q 100 0 0 100 10 600 cm\n");
    c.extend_from_slice(bi);
    c.extend_from_slice(b"\nQ\n0 1 0 rg\n300 300 40 40 re f\n");
    assemble(doc, c, dictionary! {}, dictionary! {}, dictionary! {})
}

fn marker_survived(page: &PageData) -> bool {
    ink_in_region(&page.prims, 300.0, 300.0, 341.0, 341.0)
}
