name: ✨ Feature Request
description: Suggest a new idea for a specific app.
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: app_name
    attributes:
      label: App Name
      description: Which app is this feature for?
      options:
        - alchemist
        - appstore
        - arrows
        - astronomy
        - auto
        - backup
        - calculator
        - calendar
        - camera
        - cast
        - chess
        - clock
        - code
        - communicate
        - contacts
        - education
        - email
        - euicc
        - everysync
        - files
        - findfamily
        - flashcards
        - fooddelivery
        - health
        - hub
        - keyboard
        - launcher
        - logicgate
        - logviewer
        - maps
        - measure
        - minesweeper
        - music
        - musicbrainz
        - networklocation
        - nonogram
        - notes
        - office
        - openassistant
        - passwords
        - pdf
        - photos
        - pipes
        - safefamily
        - setupwizard
        - share
        - solitaire
        - speech
        - sudoku
        - taxi
        - things
        - tools:holidaygen
        - translate
        - travel
        - tuner
        - unblockjam
        - updater
        - vpn
        - voxels
        - weather
        - web
        - wordmaker
        - youpipe
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature should be added and why is it important?
      placeholder: Describe the "what" and the "why" here.
    validations:
      required: true
