package com.vayunmathur.youpipe.ui

import android.app.Activity
import android.content.pm.ActivityInfo
import android.content.res.Configuration
import kotlinx.coroutines.flow.first
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalResources
import androidx.compose.ui.platform.LocalView
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import com.vayunmathur.library.ui.Button
import com.vayunmathur.library.ui.Card
import com.vayunmathur.library.ui.Text
import com.vayunmathur.library.util.NavBackStack
import com.vayunmathur.youpipe.R
import com.vayunmathur.youpipe.Route
import com.vayunmathur.youpipe.findActivity
import com.vayunmathur.youpipe.platform.CastPlayback
import com.vayunmathur.youpipe.rememberIsInPipMode
import com.vayunmathur.youpipe.util.VideoDetailActions
import com.vayunmathur.youpipe.util.VideoDetailUiState
import com.vayunmathur.youpipe.util.YouPipeViewModel
import com.vayunmathur.youpipe.util.DownloadManager
import kotlin.time.Instant

data class VideoChapter(val time: Int, val title: String, val previewURL: String?)
data class AudioStream(
    val url: String,
    val bitrate: Int,
    val language: String,
    val codec: String,
    val size: Long,
    val audioTrackId: String? = null,
    val displayName: String? = null,
)
data class VideoStream(val url: String, val width: Int, val height: Int, val bitrate: Int, val fps: Int, val quality: String, val codec: String, val size: Long)
data class SubtitleTrack(
    val url: String,
    val languageTag: String,      // e.g. "en", "es"
    val displayName: String,      // e.g. "English", "Spanish (auto-generated)"
    val autoGenerated: Boolean,
    val mimeType: String,         // e.g. "application/ttml+xml" or "text/vtt"
)
data class VideoData(val title: String, val views: Long, val duration: Long, val uploadDate: Instant, val thumbnailURL: String, val author: String, val authorURL: String, val authorThumbnail: String, val description: String)
data class Comment(val text: String, val author: String, val likes: Int, val dislikes: Int)

@Composable
fun LockScreenOrientation(orientation: Int) {
    val context = LocalContext.current
    DisposableEffect(orientation) {
        val activity = context.findActivity()
        val originalOrientation = activity.requestedOrientation
        activity.requestedOrientation = orientation

        onDispose {
            // Restore original orientation when leaving the screen
            activity.requestedOrientation = originalOrientation
        }
    }
}

/**
 * Binder for the video screen: loads the video, owns the fullscreen/PiP window plumbing and
 * the player itself, and hands everything else to [VideoDetailScreen] as plain values.
 */
@Composable
fun VideoPage(
    backStack: NavBackStack<Route>,
    ypvm: YouPipeViewModel,
    videoID: Long,
) {
    val context = LocalContext.current
    val resources = LocalResources.current
    val downloadedFlow = remember(videoID) { ypvm.downloadedById(videoID) }
    val downloadedVideo by downloadedFlow.collectAsState(initial = null)
    val videoState by ypvm.videoState.collectAsState()

    LaunchedEffect(videoID) {
        val downloaded = downloadedFlow.first()
        ypvm.loadVideo(videoID, downloaded)
    }
    LaunchedEffect(downloadedVideo) {
        downloadedVideo?.let { ypvm.applyDownloadedStreams(it) }
    }

    val deArrowEnabled by ypvm.deArrowEnabled.collectAsState()
    val deArrowCache by ypvm.deArrowCache.collectAsState()
    val deArrowData = if (deArrowEnabled) deArrowCache[videoID] else null

    val videoData = videoState.data?.let { data ->
        data.copy(
            title = deArrowData?.title ?: data.title,
            thumbnailURL = deArrowData?.thumbnailUrl ?: data.thumbnailURL
        )
    }
    val videoStreams = videoState.videoStreams
    val audioStreams = videoState.audioStreams
    val subtitles = videoState.subtitles
    val segments = videoState.segments
    val comments = videoState.comments
    val relatedVideos = videoState.relatedVideos

    if (videoState.error) {
        Dialog({
            ypvm.clearVideoError()
            backStack.pop()
        }) {
            Card {
                Column(Modifier.padding(16.dp)) {
                    Text(stringResource(R.string.video_load_error))
                    Spacer(Modifier.height(8.dp))
                    Button({
                        ypvm.clearVideoError()
                        backStack.pop()
                    }) {
                        Text(stringResource(R.string.action_go_back))
                    }
                }
            }
        }
    }

    var isFullscreen by remember { mutableStateOf(false) }
    // Whether fullscreen was entered by rotating rather than by the button. Rotation-entered
    // fullscreen must leave the orientation unlocked, otherwise rotating back to portrait is
    // impossible and the only way out is the exit button.
    var fullscreenFromRotation by remember { mutableStateOf(false) }
    // Set when the user leaves fullscreen while still holding the device in landscape, so that
    // auto-fullscreen doesn't immediately put them back. Cleared on the next portrait.
    var autoFullscreenSuppressed by remember { mutableStateOf(false) }

    val configuration = LocalConfiguration.current
    // smallestScreenWidthDp is the shorter edge, so unlike a window size class it gives the same
    // answer in both orientations. 600dp is the sw600dp bucket Android itself calls a tablet.
    val isPhone = configuration.smallestScreenWidthDp < 600
    val isLandscape = configuration.orientation == Configuration.ORIENTATION_LANDSCAPE
    val isInPipMode = rememberIsInPipMode()

    // A phone in landscape has no room for the description and comments, so fill the screen with
    // the video. Tablets are wide enough to keep the whole page, so they stay opt-in via the button.
    LaunchedEffect(isPhone, isLandscape, isInPipMode) {
        if (!isPhone || isInPipMode) return@LaunchedEffect
        if (isLandscape) {
            if (!isFullscreen && !autoFullscreenSuppressed) {
                isFullscreen = true
                fullscreenFromRotation = true
            }
        } else {
            autoFullscreenSuppressed = false
            if (fullscreenFromRotation) {
                isFullscreen = false
                fullscreenFromRotation = false
            }
        }
    }

    val view = LocalView.current
    LaunchedEffect(isFullscreen) {
        val window = (view.context as Activity).window
        val controller = WindowCompat.getInsetsController(window, view)

        if (isFullscreen) {
            // Hide both status bar and navigation bar
            controller.hide(WindowInsetsCompat.Type.systemBars())
            // Make it so they only reappear with a swipe and don't resize the layout
            controller.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
        } else {
            controller.show(WindowInsetsCompat.Type.systemBars())
        }
    }

    if (isFullscreen && !fullscreenFromRotation) {
        LockScreenOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE)
    }

    val activeDownloads by DownloadManager.activeDownloads.collectAsState()
    val history by ypvm.historyVideos.collectAsState()
    val progressById = remember(history) { history.associate { it.id to it.progress } }

    // ---- next and previous, for the television's remote ----
    // There is no player queue to advance and there cannot easily be one: SABR needs per-video
    // extractor state that only `loadVideo` establishes. So "next" is exactly what tapping a related
    // video does, and "previous" is the way back the user came - both of which need the back stack, so
    // both live here rather than in the player.
    val canGoNext = relatedVideos.isNotEmpty()
    val canGoPrevious = backStack.backStack.count { it is Route.VideoPage } > 1
    LaunchedEffect(canGoNext, canGoPrevious) {
        CastPlayback.update { it.copy(hasNext = canGoNext, hasPrevious = canGoPrevious) }
    }
    DisposableEffect(relatedVideos, canGoPrevious) {
        val handler: (Boolean) -> Unit = { next ->
            if (next) {
                relatedVideos.firstOrNull()?.let { backStack.add(Route.VideoPage(it.videoID)) }
            } else if (canGoPrevious) {
                backStack.pop()
            }
        }
        CastPlayback.onNavigate = handler
        // Cleared only if it is still ours. A navigation composes the incoming screen before disposing
        // the outgoing one, so an unconditional null here would undo the handler that just replaced it.
        onDispose { if (CastPlayback.onNavigate === handler) CastPlayback.onNavigate = null }
    }

    VideoDetailScreen(
        state = VideoDetailUiState(
            loaded = videoData != null,
            title = videoData?.title.orEmpty(),
            byline = videoData?.let {
                if (it.views < 0) {
                    resources.getString(
                        R.string.video_info_paid_format,
                        it.author,
                        uploadTimeAgo(context, it.uploadDate),
                    )
                } else {
                    resources.getString(
                        R.string.video_info_format,
                        it.author,
                        countString(context, it.views),
                        uploadTimeAgo(context, it.uploadDate),
                    )
                }
            }.orEmpty(),
            authorThumbnailURL = videoData?.authorThumbnail.orEmpty(),
            authorURL = videoData?.authorURL.orEmpty(),
            description = videoData?.description.orEmpty(),
            comments = comments,
            relatedVideos = relatedVideos.map { related ->
                val relatedDeArrow = if (deArrowEnabled) deArrowCache[related.videoID] else null
                val watched = progressById[related.videoID] ?: 0L
                videoRowState(
                    context = context,
                    videoInfo = related,
                    showAuthor = true,
                    percentWatched = if (related.duration > 0) (watched.toDouble() / related.duration).toFloat() else 0f,
                    deArrowTitle = relatedDeArrow?.title,
                    deArrowThumbnailURL = relatedDeArrow?.thumbnailUrl,
                )
            },
            videoStreams = videoStreams,
            audioStreams = audioStreams,
            downloaded = downloadedVideo != null,
            downloadProgress = activeDownloads[videoID]?.progress?.toFloat(),
        ),
        actions = object : VideoDetailActions {
            override fun openChannel() {
                videoData?.let { backStack.add(Route.ChannelPage(it.authorURL)) }
            }

            override fun openVideo(videoID: Long) {
                backStack.add(Route.VideoPage(videoID))
            }

            override fun download(videoUrl: String, audioUrl: String?) {
                val data = videoData ?: return
                DownloadManager.enqueueDownload(
                    context,
                    VideoInfo(data.title, videoID, data.duration, data.views, data.uploadDate, data.thumbnailURL, data.author),
                    videoUrl,
                    audioUrl,
                )
            }

            override fun cancelDownload() {
                DownloadManager.cancelDownload(context, videoID)
            }

            override fun deleteDownload() {
                downloadedVideo?.let { ypvm.deleteDownloadedVideo(it) }
            }

            override fun addToPlaylist() {
                backStack.add(Route.AddToPlaylist(videoID))
            }
        },
        fullscreen = isFullscreen,
        titleSharedKey = "youpipe-video-title-$videoID",
    ) {
        videoData?.let { data ->
            if (videoStreams.isNotEmpty()) {
                VideoPlayer(ypvm, VideoInfo(data.title, videoID, data.duration, data.views, data.uploadDate, data.thumbnailURL, data.author), videoStreams, audioStreams, subtitles, segments, isFullscreen) { fullscreen ->
                    isFullscreen = fullscreen
                    fullscreenFromRotation = false
                    autoFullscreenSuppressed = !fullscreen && isLandscape
                }
            }
        }
    }
}
