package com.vayunmathur.calendar.util

import android.content.Context
import android.util.Log
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class HolidayCountry(val code: String, val name: String)

@Serializable
data class HolidayEntry(val d: String, val n: String)

@Serializable
data class HolidayLanguage(val code: String, val name: String)

/**
 * Reads the offline holiday data bundled under `assets/holidays/`
 * (`index.json` = country list, `<CODE>.json` = that country's holidays).
 * Generated by the host-only `:tools:holidaygen` module — no network needed.
 */
object HolidayData {
    private val json = Json { ignoreUnknownKeys = true }
    @Volatile private var countriesCache: List<HolidayCountry>? = null
    @Volatile private var languagesCache: List<HolidayLanguage>? = null
    @Volatile private var countryLanguagesCache: Map<String, List<String>>? = null
    private val holidaysCache = mutableMapOf<String, List<HolidayEntry>>()

    fun countries(context: Context): List<HolidayCountry> {
        countriesCache?.let { return it }
        val loaded = loadCountries(context)
        countriesCache = loaded
        return loaded
    }

    fun languages(context: Context): List<HolidayLanguage> {
        languagesCache?.let { return it }
        val loaded = loadLanguages(context)
        languagesCache = loaded
        return loaded
    }

    fun countryLanguages(context: Context): Map<String, List<String>> {
        countryLanguagesCache?.let { return it }
        val loaded = loadCountryLanguages(context)
        countryLanguagesCache = loaded
        return loaded
    }

    fun languagesForCountry(context: Context, code: String): List<HolidayLanguage> {
        // Try country_languages.json first, fall back to scanning assets if missing
        val fromMap = countryLanguages(context)[code]
        val available = fromMap ?: run {
            // Discover by checking which language folders contain this country's file
            val allLangs = languages(context).map { it.code }
            allLangs.filter { lang ->
                try {
                    context.assets.open("holidays/$lang/$code.json").close()
                    true
                } catch (_: Exception) { false }
            }.ifEmpty { listOf("en") }
        }
        val all = languages(context).associateBy { it.code }
        return available.mapNotNull { all[it] ?: HolidayLanguage(it, it.uppercase()) }
    }

    fun holidays(context: Context, code: String, lang: String = "en"): List<HolidayEntry> {
        val key = "$lang/$code"
        holidaysCache[key]?.let { return it }
        val loaded = runCatching {
            val text = try {
                context.assets.open("holidays/$lang/$code.json").bufferedReader().use { it.readText() }
            } catch (expected: Exception) {
                // Fallback to English, then old flat path
                try {
                    context.assets.open("holidays/en/$code.json").bufferedReader().use { it.readText() }
                } catch (expectedFallback: Exception) {
                    context.assets.open("holidays/$code.json").bufferedReader().use { it.readText() }
                }
            }
            json.decodeFromString<List<HolidayEntry>>(text)
        }.onFailure { Log.e("HolidayData", "Failed reading $key.json", it) }
            .getOrDefault(emptyList())
        holidaysCache[key] = loaded
        return loaded
    }

    private fun loadCountries(context: Context): List<HolidayCountry> {
        return readAssetText(context, "holidays/index.json", "index.json")
            ?.let { runCatching { json.decodeFromString<List<HolidayCountry>>(it) }.getOrNull() }
            ?: emptyList()
    }

    private fun loadLanguages(context: Context): List<HolidayLanguage> {
        return readAssetText(context, "holidays/languages.json", "languages.json")
            ?.let { runCatching { json.decodeFromString<List<HolidayLanguage>>(it) }.getOrNull() }
            ?: emptyList()
    }

    private fun loadCountryLanguages(context: Context): Map<String, List<String>> {
        return readAssetText(context, "holidays/country_languages.json", "country_languages.json")
            ?.let { runCatching { json.decodeFromString<Map<String, List<String>>>(it) }.getOrNull() }
            ?: emptyMap()
    }

    private fun readAssetText(context: Context, assetPath: String, logName: String): String? {
        return try {
            context.assets.open(assetPath).bufferedReader().use { it.readText() }
        } catch (expected: Exception) {
            Log.e("HolidayData", "Failed reading $logName", expected)
            null
        }
    }
}
