package org.schabi.newpipe.extractor.stream

import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.exceptions.ParsingException
import org.schabi.newpipe.extractor.services.youtube.ItagItem
import org.schabi.newpipe.extractor.utils.LocaleCompat
import java.util.Locale

class SubtitlesStream : Stream {

    private val format: MediaFormat?
    private val locale: Locale
    private val autoGenerated: Boolean
    private val code: String

    class Builder {
        var id: String? = null; private set
        var content: String? = null; private set
        var isUrl: Boolean = false; private set
        var deliveryMethod: DeliveryMethod = DeliveryMethod.PROGRESSIVE_HTTP; private set
        var mediaFormat: MediaFormat? = null; private set
        var manifestUrl: String? = null; private set
        var languageCode: String? = null; private set
        var autoGenerated: Boolean? = null; private set

        fun setId(id: String): Builder { this.id = id; return this }
        fun setContent(content: String, isUrl: Boolean): Builder { this.content = content; this.isUrl = isUrl; return this }
        fun setMediaFormat(mediaFormat: MediaFormat?): Builder { this.mediaFormat = mediaFormat; return this }
        fun setDeliveryMethod(deliveryMethod: DeliveryMethod): Builder { this.deliveryMethod = deliveryMethod; return this }
        fun setManifestUrl(manifestUrl: String?): Builder { this.manifestUrl = manifestUrl; return this }
        fun setLanguageCode(languageCode: String): Builder { this.languageCode = languageCode; return this }
        fun setAutoGenerated(autoGenerated: Boolean): Builder { this.autoGenerated = autoGenerated; return this }

        @Throws(ParsingException::class)
        fun build(): SubtitlesStream {
            if (content == null) throw IllegalStateException("No valid content was specified. Please specify a valid one with setContent.")
            if (deliveryMethod == null) throw IllegalStateException(
                "The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead with setDeliveryMethod."
            )
            if (languageCode == null) throw IllegalStateException(
                "The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode."
            )
            if (autoGenerated == null) throw IllegalStateException(
                "The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated."
            )
            var finalId = id
            if (finalId == null) {
                finalId = languageCode + (mediaFormat?.let { ".${it.suffix}" } ?: "")
            }
            return SubtitlesStream(
                finalId!!, content!!, isUrl, mediaFormat, deliveryMethod,
                languageCode!!, autoGenerated!!, manifestUrl
            )
        }
    }

    @Throws(ParsingException::class)
    private constructor(
        id: String,
        content: String,
        isUrl: Boolean,
        mediaFormat: MediaFormat?,
        deliveryMethod: DeliveryMethod,
        languageCode: String,
        autoGenerated: Boolean,
        manifestUrl: String?
    ) : super(id, content, isUrl, mediaFormat, deliveryMethod, manifestUrl) {
        this.locale = LocaleCompat.forLanguageTag(languageCode)
            ?: throw ParsingException("not a valid locale language code: $languageCode")
        this.code = languageCode
        this.format = mediaFormat
        this.autoGenerated = autoGenerated
    }

    fun getExtension(): String? = format?.suffix
    fun isAutoGenerated(): Boolean = autoGenerated

    override fun equalStats(cmp: Stream?): Boolean {
        return super.equalStats(cmp) && cmp is SubtitlesStream
                && code == cmp.code
                && autoGenerated == cmp.autoGenerated
    }

    fun getDisplayLanguageName(): String = locale.getDisplayName(locale)
    fun getLanguageTag(): String = code
    fun getLocale(): Locale = locale
    override fun getItagItem(): ItagItem? = null
}
