package com.vayunmathur.keyboard.util

/** All remaining scripts: Greek through Indic, CJK composers, and the tail. */
internal val otherScriptKeyboardLayouts: List<KeyboardLayout> by lazy {
    listOf(
        KeyboardLayout(
            id = "el",
            name = "Ελληνικά",
            description = "Greek",
            rows = listOf("ςερτυθιοπ", "ασδφγηξκλ", "ζχψωβνμ"),
            alternates = mapOf(
                'α' to "ά", 'ε' to "έ", 'η' to "ή", 'ι' to "ίϊΐ", 'ο' to "ό",
                'υ' to "ύϋΰ", 'ω' to "ώ", 'σ' to "ς",
            ),
        ),
        KeyboardLayout(
            id = "he",
            name = "עברית",
            description = "Hebrew",
            rows = listOf("קראטוןםפ", "שדגכעיחלךף", "זסבהנמצתץ"),
        ),
        KeyboardLayout(
            id = "ar",
            name = "العربية",
            description = "Arabic",
            rows = listOf("ضصثقفغعهخحجد", "شسيبلاتنمكط", "ئءؤرىةوزظذ"),
            alternates = mapOf('ا' to "أإآ", 'ه' to "ة", 'و' to "ؤ", 'ي' to "ى", 'ء' to "ئؤأإ"),
        ),
        KeyboardLayout(
            id = "fa",
            name = "فارسی",
            description = "Persian",
            rows = listOf("ضصثقفغعهخحجچ", "شسیبلاتنمکگ", "ظطزرذدپوژ"),
            alternates = mapOf('ا' to "آأإ", 'ه' to "ة", 'و' to "ؤ", 'ی' to "ئي", 'ک' to "ك"),
        ),
        KeyboardLayout(
            id = "hi_inscript",
            name = "हिन्दी",
            description = "Hindi / Marathi · InScript",
            rows = listOf("ौैाीूबहगदजड़", "ोे्िुपरकतचट", "ॉंमनवलस,.य"),
            shiftedRows = listOf("औऐआईऊभङघधझढञ", "ओएअइउफऱखथछठ", "ऑँणऩऴळशष।य़"),
        ),
        // InScript, the Indian government standard: one arrangement of *sound* positions
        // shared by every Indic script, so a Bengali typist and a Gujarati typist use the
        // same fingering. The rows below are Devanagari's mapped into each script's
        // Unicode block (the blocks are deliberately parallel), with the positions whose
        // letter that script does not have removed rather than left as unassigned
        // codepoints. Shift is the second layer, as in Devanagari: no Indic script has
        // case.
        KeyboardLayout(
            id = "bn_inscript",
            name = "বাংলা",
            description = "Bengali · InScript",
            rows = listOf("ৌৈাীূবহগদজড়", "োে্িুপরকতচট", "ংমনলস,.য"),
            shiftedRows = listOf("ঔঐআঈঊভঙঘধঝঢঞ", "ওএঅইউফরখথছঠ", "ঁণনলশষ.য়"),
        ),
        KeyboardLayout(
            id = "pa_inscript",
            name = "ਪੰਜਾਬੀ",
            description = "Punjabi (Gurmukhi) · InScript",
            rows = listOf("ੌੈਾੀੂਬਹਗਦਜਡ਼", "ੋੇ੍ਿੁਪਰਕਤਚਟ", "ਂਮਨਵਲਸ,.ਯ"),
            shiftedRows = listOf("ਔਐਆਈਊਭਙਘਧਝਢਞ", "ਓਏਅਇਉਫਰਖਥਛਠ", "ਁਣਨਵਲ਼ਸ਼,.ਯ"),
        ),
        KeyboardLayout(
            id = "gu_inscript",
            name = "ગુજરાતી",
            description = "Gujarati · InScript",
            rows = listOf("ૌૈાીૂબહગદજડ઼", "ોે્િુપરકતચટ", "ૉંમનવલસ,.ય"),
            shiftedRows = listOf("ઔઐઆઈઊભઙઘધઝઢઞ", "ઓએઅઇઉફરખથછઠ", "ઑઁણનવળશષ.ય"),
        ),
        KeyboardLayout(
            id = "or_inscript",
            name = "ଓଡ଼ିଆ",
            description = "Odia · InScript",
            rows = listOf("ୌୈାୀୂବହଗଦଜଡ଼", "ୋେ୍ିୁପରକତଚଟ", "ଂମନଵଲସ,.ଯ"),
            shiftedRows = listOf("ଔଐଆଈଊଭଙଘଧଝଢଞ", "ଓଏଅଇଉଫରଖଥଛଠ", "ଁଣନଵଳଶଷ.ୟ"),
        ),
        KeyboardLayout(
            id = "th",
            name = "ไทย",
            description = "Thai · Kedmanee",
            rows = listOf("ๆไำพะัีรนยบลฃ", "ฟหกดเ้่าสวง", "ผปแอิืทมใฝ"),
            shiftedRows = listOf("๐\"ฎฑธํ๊ณฯญฐ,ฅ", "ฤฆฏโฌ็๋ษศซ.", "()ฉฮฺ์?ฒฬฦ"),
        ),
        // --- Composed scripts (see com.vayunmathur.keyboard.ime.Composer) ---
        KeyboardLayout(
            id = "ko_dubeolsik",
            name = "한국어",
            description = "Korean · 두벌식 (Dubeolsik)",
            rows = listOf("ㅂㅈㄷㄱㅅㅛㅕㅑㅐㅔ", "ㅁㄴㅇㄹㅎㅗㅓㅏㅣ", "ㅋㅌㅊㅍㅠㅜㅡ"),
            shiftedRows = listOf("ㅃㅉㄸㄲㅆㅛㅕㅑㅒㅖ", "ㅁㄴㅇㄹㅎㅗㅓㅏㅣ", "ㅋㅌㅊㅍㅠㅜㅡ"),
            composer = ComposerKind.HANGUL,
        ),
        KeyboardLayout(
            id = "zh_pinyin",
            name = "中文 (拼音)",
            description = "Chinese · Pinyin, simplified",
            rows = Layouts.LETTER_ROWS,
            composer = ComposerKind.PINYIN_SIMPLIFIED,
            comma = "，",
            period = "。",
        ),
        KeyboardLayout(
            id = "zh_pinyin_tc",
            name = "中文 (拼音・繁)",
            description = "Chinese · Pinyin, traditional",
            rows = Layouts.LETTER_ROWS,
            composer = ComposerKind.PINYIN_TRADITIONAL,
            comma = "，",
            period = "。",
        ),
        KeyboardLayout(
            id = "zh_bopomofo",
            name = "中文 (注音)",
            description = "Chinese · Bopomofo 大千, traditional",
            rows = listOf(
                "ㄅㄉˇˋㄓˊ˙ㄚㄞㄢㄦ",
                "ㄆㄊㄍㄐㄔㄗㄧㄛㄟㄣ",
                "ㄇㄋㄎㄑㄕㄘㄨㄜㄠㄤ",
                "ㄈㄌㄏㄒㄖㄙㄩㄝㄡㄥ",
            ),
            composer = ComposerKind.BOPOMOFO,
            comma = "，",
            period = "。",
        ),
        KeyboardLayout(
            id = "ja_romaji",
            name = "日本語 (ローマ字)",
            description = "Japanese · romaji to kana; shift types katakana",
            rows = Layouts.LETTER_ROWS,
            composer = ComposerKind.ROMAJI,
            comma = "、",
            period = "。",
        ),
        KeyboardLayout(
            id = "ja_kana",
            name = "日本語 (かな)",
            description = "Japanese · JIS kana",
            rows = listOf(
                "ぬふあうえおやゆよわほへ",
                "たていすかんなにらせ゛゜",
                "ちとしはきくまのりれけむ",
                "つさそひこみもねるめろ",
            ),
            shiftedRows = listOf(
                "ぬふぁぅぇぉゃゅょをーへ",
                "たてぃすかんなにらせ゛゜",
                "ちとしはきくまのりれけむ",
                "っさそひこみもね、。・",
            ),
            composer = ComposerKind.KANA,
            comma = "、",
            period = "。",
        ),
        KeyboardLayout(
            id = "ka",
            name = "ქართული",
            description = "Georgian",
            rows = listOf("ქწერტყუიოპ", "ასდფგჰჯკლ", "ზხცვბნმ"),
            shiftedRows = listOf("ქჭეღთყუიოპ", "აშდფგჰჟკლ", "ძხჩვბნმ"),
        ),
        KeyboardLayout(
            id = "ta_inscript",
            name = "தமிழ்",
            description = "Tamil · InScript",
            rows = listOf("ௌைாீூஹஜ", "ோே்ிுபரகதசட", "ஂமநவலஸ,.ய"),
            shiftedRows = listOf("ஔஐஆஈஊஙஜ", "ஓஏஅஇஉபறகதசட", "ஂணனழளஶஷ.ய"),
            alternates = mapOf('ே' to "ெஎ", 'ோ' to "ொஒ", 'ஂ' to "ஃ", 'ந' to "ஞ", 'ௌ' to "ௗ"),
        ),
        KeyboardLayout(
            id = "te_inscript",
            name = "తెలుగు",
            description = "Telugu · InScript",
            rows = listOf("ౌైాీూబహగదజడ఼", "ోే్ిుపరకతచట", "ంమనవలస,.య"),
            shiftedRows = listOf("ఔఐఆఈఊభఙఘధఝఢఞ", "ఓఏఅఇఉఫఱఖథఛఠ", "ఁణనఴళశష.య"),
            alternates = mapOf('ే' to "ెఎ", 'ో' to "ొఒ", 'ం' to "ఃఀ", 'ర' to "ఋృౠ", 'ల' to "ఌౢ", 'చ' to "ౘ", 'జ' to "ౙ", 'ా' to "ఽ"),
        ),
        KeyboardLayout(
            id = "kn_inscript",
            name = "ಕನ್ನಡ",
            description = "Kannada · InScript",
            rows = listOf("ೌೈಾೀೂಬಹಗದಜಡ಼", "ೋೇ್ಿುಪರಕತಚಟ", "ಂಮನವಲಸ,.ಯ"),
            shiftedRows = listOf("ಔಐಆಈಊಭಙಘಧಝಢಞ", "ಓಏಅಇಉಫಱಖಥಛಠ", "ಁಣನವಳಶಷ.ಯ"),
            alternates = mapOf('ೇ' to "ೆಎ", 'ೋ' to "ೊಒ", 'ಂ' to "ಃ", 'ರ' to "ಋೃೠ", 'ಲ' to "ಌೞ", 'ಾ' to "ಽ"),
        ),
        KeyboardLayout(
            id = "ml_inscript",
            name = "മലയാളം",
            description = "Malayalam · InScript",
            rows = listOf("ൌൈാീൂബഹഗദജഡ഼", "ോേ്ിുപരകതചട", "ംമനവലസ,.യ"),
            shiftedRows = listOf("ഔഐആഈഊഭങഘധഝഢഞ", "ഓഏഅഇഉഫറഖഥഛഠ", "ഁണഩഴളശഷ.യ"),
            alternates = mapOf('േ' to "െഎ", 'ോ' to "ൊഒ", 'ം' to "ഃ", 'ര' to "ഋൃർ", 'ല' to "ഌൽൾ", 'ന' to "ൻൺ", 'ക' to "ൿ", 'ാ' to "ഽ", 'ൌ' to "ൗ"),
        ),
        KeyboardLayout(
            id = "hy",
            name = "Հայերեն",
            description = "Armenian · alphabetical",
            rows = listOf("աբգդեզէըթժ", "իլխծկհձղճմ", "յնշոչպջռսվ", "տրցւփքօֆև"),
        ),
        KeyboardLayout(
            id = "lo",
            name = "ລາວ",
            description = "Lao · alphabetical",
            rows = listOf("ກຂຄງຈສຊຍດ", "ຕຖທນບປຜຝພ", "ຟມຢຣລວຫອຮ"),
            shiftedRows = listOf("ະັາຳິີຶືຸ", "ູົຼຽເແໂໃໄ", "່້໊໋ໍ໌ໆໜໝ"),
        ),
        KeyboardLayout(
            id = "km",
            name = "ភាសាខ្មែរ",
            description = "Khmer · alphabetical",
            rows = listOf("កខគឃងចឆជឈញដ", "ឋឌឍណតថទធនបផ", "ពភមយរលវឝឞសហ", "ឡអឣឤឥឦឧឨឩ"),
            shiftedRows = listOf("ឪឫឬឭឮឯឰឱឲឳ឴", "឵ាិីឹឺុូួើឿ", "ៀេែៃោៅំះៈ៉៊", "់៌៍៎៏័៑្៓"),
        ),
        KeyboardLayout(
            id = "si",
            name = "සිංහල",
            description = "Sinhala · alphabetical",
            rows = listOf("අආඇඈඉඊඋඌඍඎ", "ඏඐඑඒඓඔඕඖකඛ", "ගඝඞඟචඡජඣඤඥ", "ඦටඨඩඪණඬතථ"),
            shiftedRows = listOf("දධනඳපඵබභමඹ", "යරලවශෂසහළෆ", "්ාැෑිීුූෘෙ", "ේෛොෝෞෟෲෳං"),
        ),
        KeyboardLayout(
            id = "my",
            name = "မြန်မာ",
            description = "Burmese · alphabetical",
            rows = listOf("ကခဂဃငစဆဇ", "ဈဉညဋဌဍဎဏ", "တထဒဓနပဖဗ", "ဘမယရလဝသဟ"),
            shiftedRows = listOf("ဠအဢဣဤဥဦဧ", "ဨဩဪါာိီု", "ူေဲဳဴဵံ့", "း္်ျြွှ။"),
        ),
        KeyboardLayout(
            id = "bo",
            name = "བོད་ཡིག",
            description = "Tibetan · alphabetical",
            rows = listOf("ཀཁགགྷངཅཆཇ", "ཉཊཋཌཌྷཎཏཐ", "དདྷནཔཕབབྷམ", "ཙཚཛཛྷཝཞཟའ"),
            shiftedRows = listOf("ཡརལཤཥསཧཨ", "ཀྵཪཫཬཱཱིིུ", "ཱུྲྀཷླྀཹེཻོ", "ཽཾཿ྄ཱྀྀྂྃ"),
        ),
        KeyboardLayout(
            id = "dv",
            name = "ދިވެހި",
            description = "Dhivehi (Thaana) · alphabetical",
            rows = listOf("ހށނރބޅކ", "އވމފދތލ", "ގޏސޑޒޓޔ", "ޕޖޗޘ"),
            shiftedRows = listOf("ޙޚޛޜޝޞޟ", "ޠޡޢޣޤޥަ", "ާިީުޫެޭ", "ޮޯްޱ"),
        ),
        KeyboardLayout(
            id = "chr",
            name = "ᏣᎳᎩ",
            description = "Cherokee · syllabary",
            rows = listOf("ᎠᎡᎢᎣᎤᎥᎦᎧᎨᎩᎪ", "ᎫᎬᎭᎮᎯᎰᎱᎲᎳᎴᎵ", "ᎶᎷᎸᎹᎺᎻᎼᎽᎾᎿᏀ", "ᏁᏂᏃᏄᏅᏆᏇᏈᏉᏊ"),
            shiftedRows = listOf("ᏋᏌᏍᏎᏏᏐᏑᏒᏓᏔᏕ", "ᏖᏗᏘᏙᏚᏛᏜᏝᏞᏟᏠ", "ᏡᏢᏣᏤᏥᏦᏧᏨᏩᏪᏫ", "ᏬᏭᏮᏯᏰᏱᏲᏳᏴᏵ"),
        ),
        KeyboardLayout(
            id = "am",
            name = "አማርኛ / ትግርኛ",
            description = "Amharic / Tigrinya · consonant then vowel",
            rows = listOf("ሀለሐመሠረሰሸቀቐበ", "ቨተቸኀነኘከኸዐዘዠ", "የደዸጀገጘጠጨጰጸፀ", "ፈፐአኡኢኣኤእኦ"),
            composer = ComposerKind.ETHIOPIC,
        ),
        KeyboardLayout(
            id = "ur",
            name = "اردو",
            description = "Urdu · Pakistan",
            rows = listOf("طصھدٹپتبجح", "مورنلہاکی", "قفےسشغع"),
            alternates = mapOf('ت' to "ث", 'ج' to "چ", 'ح' to "خ", 'د' to "ڈذ", 'ر' to "ڑزژ", 'ص' to "ض", 'ط' to "ظ", 'ک' to "گ", 'ن' to "ں", 'ا' to "آأء", 'و' to "ؤ", 'ی' to "ئ", 'ہ' to "ھۃ"),
        ),
        KeyboardLayout(
            id = "ps",
            name = "پښتو",
            description = "Pashto · Afghanistan",
            rows = listOf("ضصثقفغعهخحجچ", "شسیبلاتنمکگ", "ظطزرذدپوژ"),
            alternates = mapOf('ت' to "ټ", 'د' to "ډ", 'ر' to "ړ", 'ز' to "ږ", 'س' to "ښ", 'ک' to "ګ", 'ن' to "ڼ", 'ی' to "ۍېئ", 'ا' to "آأ", 'ه' to "ة", 'چ' to "څ", 'ج' to "ځ", 'و' to "ؤ"),
        ),
        // --- Devanagari and Bengali variants: the same InScript arrangement, listed
        // separately because a Nepali speaker looks for नेपाली, not हिन्दी. ---
        KeyboardLayout(
            id = "ne_inscript",
            name = "नेपाली",
            description = "Nepali · InScript",
            rows = listOf("ौैाीूबहगदजड़", "ोे्िुपरकतचट", "ॉंमनवलस,.य"),
            shiftedRows = listOf("औऐआईऊभङघधझढञ", "ओएअइउफऱखथछठ", "ऑँणऩऴळशष।य़"),
        ),
        KeyboardLayout(
            id = "mr_inscript",
            name = "मराठी",
            description = "Marathi · InScript",
            rows = listOf("ौैाीूबहगदजड़", "ोे्िुपरकतचट", "ॉंमनवलस,.य"),
            shiftedRows = listOf("औऐआईऊभङघधझढञ", "ओएअइउफऱखथछठ", "ऑँणऩऴळशष।य़"),
        ),
        KeyboardLayout(
            id = "sa_inscript",
            name = "संस्कृतम्",
            description = "Sanskrit · InScript",
            rows = listOf("ौैाीूबहगदजड़", "ोे्िुपरकतचट", "ॉंमनवलस,.य"),
            shiftedRows = listOf("औऐआईऊभङघधझढञ", "ओएअइउफऱखथछठ", "ऑँणऩऴळशष।य़"),
        ),
        KeyboardLayout(
            id = "as_inscript",
            name = "অসমীয়া",
            description = "Assamese · InScript",
            rows = listOf("ৌৈাীূবহগদজড়", "োে্িুপরকতচট", "ংমনলস,.য"),
            shiftedRows = listOf("ঔঐআঈঊভঙঘধঝঢঞ", "ওএঅইউফরখথছঠ", "ঁণনলশষ.য়"),
            // Assamese uses ৰ and ৱ where Bengali uses র and ব.
            alternates = mapOf('র' to "ৰ", 'ব' to "ৱ"),
        ),
    )
}
